package org.markup.poet.asciidoc.render

/**
 * Maintains state during HTML rendering.
 * 
 * RenderContext tracks rendering state such as generated IDs, warnings,
 * and provides access to configuration and theme. It ensures unique ID
 * generation for elements like headings and handles collision resolution.
 * 
 * This class is instantiated once per rendering operation and passed through
 * the rendering pipeline to maintain consistent state.
 * 
 * @param config The rendering configuration containing theme and output options
 */
class RenderContext(
    val config: RenderConfig
) {
    /**
     * The theme to use for CSS class generation.
     * Convenience accessor for config.theme.
     */
    val theme: Theme = config.theme
    
    /**
     * Map tracking generated IDs and their occurrence counts.
     * Used to ensure unique IDs by appending suffixes when collisions occur.
     */
    private val idMap = mutableMapOf<String, Int>()
    
    /**
     * List of warning messages collected during rendering.
     * Warnings are non-fatal issues like unknown node types or skipped content.
     */
    private val warnings = mutableListOf<String>()
    
    /**
     * Tracks heading levels to validate hierarchy.
     * Used to detect skipped heading levels (e.g., h1 -> h3 without h2).
     */
    private var lastHeadingLevel: Int = 0
    
    /**
     * Collects heading information for table of contents generation.
     * Each entry contains (level, id, text).
     */
    private val headings = mutableListOf<Triple<Int, String, String>>()
    
    /**
     * Generates a unique HTML ID from the given text.
     * 
     * The ID is generated by:
     * 1. Converting text to lowercase
     * 2. Replacing non-alphanumeric sequences with hyphens
     * 3. Trimming leading/trailing hyphens
     * 4. Appending a numeric suffix if the ID already exists
     * 
     * Examples:
     * - "Introduction" -> "introduction"
     * - "Getting Started" -> "getting-started"
     * - "Introduction" (second occurrence) -> "introduction-1"
     * - "Introduction" (third occurrence) -> "introduction-2"
     * 
     * @param text The text to convert to an ID (typically heading text)
     * @return A unique HTML ID string
     */
    fun generateId(text: String): String {
        // Convert to lowercase and replace non-alphanumeric characters with hyphens
        val base = text
            .lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .trim('-')
        
        // Handle empty base case (e.g., text with only special characters)
        val normalizedBase = if (base.isEmpty()) "section" else base
        
        // Get the current count for this base ID
        val count = idMap[normalizedBase] ?: 0
        
        // Increment the count for next time
        idMap[normalizedBase] = count + 1
        
        // Return base ID for first occurrence, or base-N for subsequent occurrences
        return if (count == 0) normalizedBase else "$normalizedBase-$count"
    }
    
    /**
     * Registers a heading for table of contents generation and validates hierarchy.
     * 
     * This method:
     * 1. Validates that heading levels don't skip (e.g., h1 -> h3 without h2)
     * 2. Records the heading for TOC generation
     * 
     * @param level The heading level (1-6)
     * @param id The generated ID for the heading
     * @param text The heading text
     */
    fun registerHeading(level: Int, id: String, text: String) {
        // Validate heading hierarchy
        if (lastHeadingLevel > 0 && level > lastHeadingLevel + 1) {
            logWarning("Heading hierarchy skipped from h$lastHeadingLevel to h$level (missing h${lastHeadingLevel + 1})")
        }
        
        lastHeadingLevel = level
        headings.add(Triple(level, id, text))
    }
    
    /**
     * Returns all headings collected during rendering.
     * Each entry contains (level, id, text).
     * 
     * @return List of heading information for TOC generation
     */
    fun getHeadings(): List<Triple<Int, String, String>> = headings.toList()
    
    /**
     * Generates a table of contents HTML from collected headings.
     * 
     * The TOC is rendered as a `<nav>` element with nested lists that
     * reflect the heading hierarchy. Each heading becomes a link to its anchor.
     * 
     * @param escaper The HTML escaper to use for text content
     * @return HTML string for the table of contents, or empty string if no headings
     */
    fun generateToc(escaper: HtmlEscaper): String {
        if (headings.isEmpty()) {
            return ""
        }
        
        val builder = StringBuilder()
        builder.append("<nav class=\"toc\" role=\"navigation\" aria-label=\"Table of Contents\">\n")
        builder.append("  <h2>Table of Contents</h2>\n")
        
        var currentLevel = 0
        val levelStack = mutableListOf<Int>()
        
        for ((level, id, text) in headings) {
            val escapedText = escaper.escapeHtml(text)
            val escapedId = escaper.escapeAttribute(id)
            
            // Close lists if we're going back up the hierarchy
            while (levelStack.isNotEmpty() && levelStack.last() >= level) {
                levelStack.removeLast()
                builder.append("  ".repeat(levelStack.size + 1))
                builder.append("</ul>\n")
            }
            
            // Open new lists if we're going deeper
            while (currentLevel < level) {
                if (currentLevel > 0) {
                    builder.append("  ".repeat(levelStack.size + 1))
                    builder.append("<ul>\n")
                    levelStack.add(currentLevel)
                } else {
                    builder.append("  <ul>\n")
                }
                currentLevel++
            }
            
            // Add the list item with link
            builder.append("  ".repeat(levelStack.size + 2))
            builder.append("<li><a href=\"#$escapedId\">$escapedText</a></li>\n")
            
            currentLevel = level
        }
        
        // Close remaining open lists
        while (levelStack.isNotEmpty()) {
            levelStack.removeLast()
            builder.append("  ".repeat(levelStack.size + 1))
            builder.append("</ul>\n")
        }
        
        if (currentLevel > 0) {
            builder.append("  </ul>\n")
        }
        
        builder.append("</nav>")
        
        return builder.toString()
    }
    
    /**
     * Processes attribute handlers for a node and returns additional HTML attributes.
     * 
     * This method invokes all registered attribute handlers for the node and
     * collects their output into a single map of HTML attributes.
     * 
     * @param node The AST node being rendered
     * @return Map of HTML attribute names to values from all handlers
     */
    fun processAttributeHandlers(node: org.markup.poet.asciidoc.ast.AstNode): Map<String, String> {
        val result = mutableMapOf<String, String>()
        
        // Process each registered attribute handler
        for ((name, handler) in config.attributeHandlers) {
            val attributes = handler.processAttributes(node, this)
            result.putAll(attributes)
        }
        
        return result
    }
    
    /**
     * Logs a warning message.
     * 
     * Warnings are collected and can be retrieved after rendering completes.
     * They indicate non-fatal issues that don't prevent rendering but may
     * indicate problems with the input or unexpected conditions.
     * 
     * @param message The warning message to log
     */
    fun logWarning(message: String) {
        warnings.add(message)
    }
    
    /**
     * Returns all warnings collected during rendering.
     * 
     * @return An immutable list of warning messages
     */
    fun getWarnings(): List<String> = warnings.toList()
}
